export default {
  employeeCode: "",
  fullName: "",
  deparmentId: "",
  gender: 1,
  dateOfBirth: null,
  identityNumber: "",
  identityDate: null,
  identityPlace: "",
  positionName: "",
  address: "",
  phoneNumber: "",
  landlinePhone: "",
  email: "",
  bankAccount: "",
  bankName: "",
  bankBranch: "",
};
